//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statystyki_2018.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SerwisWymianySoap")]
    public interface SerwisWymianySoap {
        
        // CODEGEN: Generating message contract since element name NrWydzialu from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DaneWXml", ReplyAction="*")]
        Statystyki_2018.ServiceReference1.DaneWXmlResponse DaneWXml(Statystyki_2018.ServiceReference1.DaneWXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DaneWXml", ReplyAction="*")]
        System.Threading.Tasks.Task<Statystyki_2018.ServiceReference1.DaneWXmlResponse> DaneWXmlAsync(Statystyki_2018.ServiceReference1.DaneWXmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DaneWXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DaneWXml", Namespace="http://tempuri.org/", Order=0)]
        public Statystyki_2018.ServiceReference1.DaneWXmlRequestBody Body;
        
        public DaneWXmlRequest() {
        }
        
        public DaneWXmlRequest(Statystyki_2018.ServiceReference1.DaneWXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DaneWXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NrWydzialu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string repertorium;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nrSprawy;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rodzaj;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string connection;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int rok;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string kwerendaZapytujaca;
        
        public DaneWXmlRequestBody() {
        }
        
        public DaneWXmlRequestBody(string NrWydzialu, string repertorium, int nrSprawy, string rodzaj, string connection, int rok, string kwerendaZapytujaca) {
            this.NrWydzialu = NrWydzialu;
            this.repertorium = repertorium;
            this.nrSprawy = nrSprawy;
            this.rodzaj = rodzaj;
            this.connection = connection;
            this.rok = rok;
            this.kwerendaZapytujaca = kwerendaZapytujaca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DaneWXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DaneWXmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public Statystyki_2018.ServiceReference1.DaneWXmlResponseBody Body;
        
        public DaneWXmlResponse() {
        }
        
        public DaneWXmlResponse(Statystyki_2018.ServiceReference1.DaneWXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DaneWXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DaneWXmlResult;
        
        public DaneWXmlResponseBody() {
        }
        
        public DaneWXmlResponseBody(string DaneWXmlResult) {
            this.DaneWXmlResult = DaneWXmlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SerwisWymianySoapChannel : Statystyki_2018.ServiceReference1.SerwisWymianySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerwisWymianySoapClient : System.ServiceModel.ClientBase<Statystyki_2018.ServiceReference1.SerwisWymianySoap>, Statystyki_2018.ServiceReference1.SerwisWymianySoap {
        
        public SerwisWymianySoapClient() {
        }
        
        public SerwisWymianySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerwisWymianySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerwisWymianySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerwisWymianySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Statystyki_2018.ServiceReference1.DaneWXmlResponse Statystyki_2018.ServiceReference1.SerwisWymianySoap.DaneWXml(Statystyki_2018.ServiceReference1.DaneWXmlRequest request) {
            return base.Channel.DaneWXml(request);
        }
        
        public string DaneWXml(string NrWydzialu, string repertorium, int nrSprawy, string rodzaj, string connection, int rok, string kwerendaZapytujaca) {
            Statystyki_2018.ServiceReference1.DaneWXmlRequest inValue = new Statystyki_2018.ServiceReference1.DaneWXmlRequest();
            inValue.Body = new Statystyki_2018.ServiceReference1.DaneWXmlRequestBody();
            inValue.Body.NrWydzialu = NrWydzialu;
            inValue.Body.repertorium = repertorium;
            inValue.Body.nrSprawy = nrSprawy;
            inValue.Body.rodzaj = rodzaj;
            inValue.Body.connection = connection;
            inValue.Body.rok = rok;
            inValue.Body.kwerendaZapytujaca = kwerendaZapytujaca;
            Statystyki_2018.ServiceReference1.DaneWXmlResponse retVal = ((Statystyki_2018.ServiceReference1.SerwisWymianySoap)(this)).DaneWXml(inValue);
            return retVal.Body.DaneWXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Statystyki_2018.ServiceReference1.DaneWXmlResponse> Statystyki_2018.ServiceReference1.SerwisWymianySoap.DaneWXmlAsync(Statystyki_2018.ServiceReference1.DaneWXmlRequest request) {
            return base.Channel.DaneWXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Statystyki_2018.ServiceReference1.DaneWXmlResponse> DaneWXmlAsync(string NrWydzialu, string repertorium, int nrSprawy, string rodzaj, string connection, int rok, string kwerendaZapytujaca) {
            Statystyki_2018.ServiceReference1.DaneWXmlRequest inValue = new Statystyki_2018.ServiceReference1.DaneWXmlRequest();
            inValue.Body = new Statystyki_2018.ServiceReference1.DaneWXmlRequestBody();
            inValue.Body.NrWydzialu = NrWydzialu;
            inValue.Body.repertorium = repertorium;
            inValue.Body.nrSprawy = nrSprawy;
            inValue.Body.rodzaj = rodzaj;
            inValue.Body.connection = connection;
            inValue.Body.rok = rok;
            inValue.Body.kwerendaZapytujaca = kwerendaZapytujaca;
            return ((Statystyki_2018.ServiceReference1.SerwisWymianySoap)(this)).DaneWXmlAsync(inValue);
        }
    }
}
